"""
Monty-based REPL environment for RLM.
This module provides a sandboxed Python execution environment using the Monty interpreter.
"""

import json
import time
from dataclasses import dataclass
from typing import Any, Optional

import pydantic_monty

from rlm import RLM


class Sub_RLM(RLM):
    """Recursive LLM client for REPL environment with fixed configuration."""

    def __init__(self, model: str = "gpt-4o-mini"):
        from rlm.utils.llm import OpenAIClient

        self.model = model
        self.client = OpenAIClient(model=model)

    def completion(self, prompt: str | list[dict[str, str]]) -> str:
        """
        Simple LM query for sub-LM call.
        """
        try:
            response = self.client.completion(messages=prompt, timeout=300)
            return response
        except Exception as e:
            return f"Error making LLM query: {str(e)}"

    def cost_summary(self) -> dict[str, float]:
        raise NotImplementedError("Cost tracking is not implemented for the Sub-RLM.")

    def reset(self):
        raise NotImplementedError("Reset is not implemented for the Sub-RLM.")


@dataclass
class REPLResult:
    stdout: str
    stderr: str
    locals: dict[str, Any]
    execution_time: float

    def __init__(
        self,
        stdout: str,
        stderr: str,
        locals: dict[str, Any],
        execution_time: float | None = None,
    ):
        self.stdout = stdout
        self.stderr = stderr
        self.locals = locals
        self.execution_time = execution_time if execution_time is not None else 0.0

    def __str__(self):
        return f"REPLResult(stdout={self.stdout}, stderr={self.stderr}, locals={self.locals}, execution_time={self.execution_time})"


class REPLEnv:
    """
    A sandboxed REPL environment using the Monty interpreter.
    This provides a secure execution environment for code generated by the RLM.
    """

    def __init__(
        self,
        recursive_model: str = "gpt-4o-mini",
        context_json: Optional[dict[str, Any] | list[Any]] = None,
        context_str: Optional[str] = None,
        setup_code: str | None = None,
    ):
        self.recursive_model = recursive_model
        self.locals: dict[str, Any] = {}
        self._stdout_buffer = ""
        self._stderr_buffer = ""

        self.sub_rlm: RLM = Sub_RLM(model=recursive_model)

        self.load_context(context_json, context_str)

        if setup_code:
            self.code_execution(setup_code)

    def load_context(
        self,
        context_json: Optional[dict[str, Any] | list[Any]] = None,
        context_str: Optional[str] = None,
    ):
        """Load context data into the REPL environment."""
        if context_json is not None:
            context_code = f"""
import json
context = {json.dumps(context_json)}
"""
            self.code_execution(context_code)

        if context_str is not None:
            context_code = f"""
context = '''{context_str}'''
"""
            self.code_execution(context_code)

    def _build_code_with_context(self, code: str, context_vars: dict[str, Any] | None = None) -> str:
        """Build the full code with context variables."""
        full_code = ""
        if context_vars:
            for var_name, var_value in context_vars.items():
                full_code += f"{var_name} = {repr(var_value)}\n"
        full_code += code
        return full_code

    def code_execution(self, code: str) -> REPLResult:
        """
        Execute Python code in the Monty sandbox.
        """
        start_time = time.time()

        stdout_capture: list[str] = []
        stderr_capture: list[str] = []

        def print_callback(text: str):
            stdout_capture.append(text)

        full_code = self._build_code_with_context(code, self.locals.copy())

        try:
            m = pydantic_monty.Monty(
                full_code,
                inputs=[],
                script_name="repl_exec.py",
            )

            result = m.run(inputs={}, print_callback=print_callback)

            if isinstance(result, pydantic_monty.MontyComplete):
                stdout_content = "\n".join(stdout_capture)
                stderr_content = ""
                if result.output is not None:
                    stdout_content += f"\n{repr(result.output)}"
            else:
                stdout_content = "\n".join(stdout_capture)
                stderr_content = "Execution did not complete"

        except pydantic_monty.MontySyntaxError as e:
            stderr_content = f"Syntax Error: {e}"
            stdout_content = "\n".join(stdout_capture)
        except pydantic_monty.MontyRuntimeError as e:
            stderr_content = f"Runtime Error: {e}"
            stdout_content = "\n".join(stdout_capture)
        except Exception as e:
            stderr_content = f"Error: {str(e)}"
            stdout_content = "\n".join(stdout_capture)

        end_time = time.time()
        execution_time = end_time - start_time

        self._stdout_buffer = stdout_content
        self._stderr_buffer = stderr_content

        self.locals["_stdout"] = stdout_content
        self.locals["_stderr"] = stderr_content

        return REPLResult(stdout_content, stderr_content, self.locals.copy(), execution_time)

    def get_cost_summary(self):
        raise NotImplementedError("Cost tracking is not implemented for the REPL Environment.")
